export type Language = 'en' | 'te' | 'kn';

export const translations: Record<Language, Record<string, string>> = {
  en: {
    // Top Bar & Branding
    appTitle: 'Next Bus',
    appSubtitle: 'Effortless Urban Mobility',

    // Tabs
    home: 'Home',
    map: 'Map',
    search: 'Search',
    alerts: 'Alerts',
    profile: 'Profile',

    // Home Dashboard
    whereToday: 'Where to today?',
    searchPlaceholder: 'Search destinations, lines, or stops',
    findRoutes: 'Find Routes',
    from: 'From — select boarding stop',
    to: 'To — select destination stop',
    smartPicks: 'Smart Picks',
    seeAll: 'See all',
    savedRoutes: 'Saved Routes',
    manage: 'Manage',
    transitUpdates: 'Transit Updates',
    activeBuses: 'Active Buses',
    network: 'Network',
    activeAlerts: 'Active Alerts',
    noSavedRoutes: 'No saved routes yet',
    noSavedRoutesSub: 'Search your daily route to bookmark it here',
    allClear: 'All services running normally across the network',
    availableSoon: 'Available Soon',
    monthlyPass: 'Unlimited Monthly Pass',
    monthlyPassDesc: 'Save up to 40% on your daily commute with the NXTBus Digital Pass.',

    // Route Results & Cards
    eta: 'ETA',
    crowd: 'Crowd',
    fare: 'Fare',
    speed: 'Speed',
    lowCrowd: 'Low Crowd',
    medCrowd: 'Medium Crowd',
    highCrowd: 'High Crowd',
    returnDirection: 'Return direction',
    availableRoutes: 'AVAILABLE ROUTES',
    noRoutesFound: 'NO ROUTES FOUND',
    planYourTrip: 'Plan your trip',
    popularDestinations: 'POPULAR DESTINATIONS',
    exploreMap: 'Explore Full City Map',

    // Map & Live Radar
    live: 'Live',
    connecting: 'Connecting…',
    busesLive: 'buses live',
    clearFilter: '✕ Clear Filter',
    locate: 'Locate Me',
    nextStop: 'Next stop',
    passed: 'Passed',
    departed: 'Departed',

    // Safety & SOS
    sos: 'SOS',
    emergencyConfirmation: 'Emergency confirmation',
    emergencySubtitle: 'Confirm to notify emergency services and trusted contacts.',
    pressAndHold: 'PRESS & HOLD',
    alertSent: 'ALERT SENT',
    sharingLiveLocation: 'Sharing live location…',
    liveLocationShared: 'Live location shared',
    notifyContacts: 'NOTIFY CONTACTS',
    edit: 'Edit',
    callEmergency: 'Call Emergency Services (112)',
    cancelReturn: 'Cancel & Return',
    trustedContacts: 'Emergency Contacts',
    addContact: 'Add Contact',
    saveContact: 'Save Contact',

    // Alerts & Notifications
    pushNotifications: 'Push Notifications',
    manageTransitUpdates: 'Manage all your transit updates',
    activeSubscriptions: 'ACTIVE ROUTE SUBSCRIPTIONS',
    recentUpdates: 'RECENT UPDATES',
    noUpdates: 'No recent service updates 🎉',
    pause: 'Pause',
    resume: 'Resume',
    delete: 'Delete',
    setAlert: 'Set Alert',
    aiProactiveMode: 'AI-Proactive (Recommended)',
    aiProactiveDesc: "We'll notify you exactly when to leave based on your location and bus ETA.",
    customAlarmMode: 'Custom Alarm',
    customAlarmDesc: 'Get notified when the bus is X minutes away from your stop.',

    // Profile & Settings
    commuter: 'Commuter',
    trips: 'Trips',
    timeSaved: 'Time Saved',
    co2Saved: 'CO₂ Saved',
    settings: 'Settings',
    language: 'Language',
    darkMode: 'Dark Mode',
    logout: 'Log out',
    helpCenter: 'Help Center',
    safetySettings: 'Safety & SOS settings',
    smartPickPreferences: 'Smart Pick preferences',
    weeklyReportCard: 'Weekly Bus Report Card',

    // Report Card
    weeklyReport: 'Weekly Report Card',
    onTimeRate: 'On-Time Rate',
    mostReliableRoute: 'Most Reliable Route',
    avgWaitTime: 'Avg. Wait Time',
    shareOnWhatsApp: 'Share on WhatsApp',
  },

  te: {
    // Top Bar & Branding
    appTitle: 'నెక్స్ట్ బస్',
    appSubtitle: 'సులభమైన నగర ప్రయాణం',

    // Tabs
    home: 'హోమ్',
    map: 'మ్యాప్',
    search: 'శోధన',
    alerts: 'హెచ్చరికలు',
    profile: 'ప్రొఫైల్',

    // Home Dashboard
    whereToday: 'ఈ రోజు ఎక్కడికి వెళ్లాలి?',
    searchPlaceholder: 'గమ్యస్థానాలు, మార్గాలు లేదా స్టాప్‌లను శోధించండి',
    findRoutes: 'మార్గాలు కనుగొనండి',
    from: 'నుండి — ఎక్కే స్టాప్‌ను ఎంచుకోండి',
    to: 'వరకు — దిగే స్టాప్‌ను ఎంచుకోండి',
    smartPicks: 'స్మార్ట్ ఎంపికలు',
    seeAll: 'అన్నీ చూడండి',
    savedRoutes: 'సేవ్ చేసిన మార్గాలు',
    manage: 'నిర్వహించండి',
    transitUpdates: 'ట్రాన్సిట్ నవీకరణలు',
    activeBuses: 'యాక్టివ్ బస్సులు',
    network: 'నెట్‌వర్క్',
    activeAlerts: 'యాక్టివ్ హెచ్చరికలు',
    noSavedRoutes: 'ఇంకా సేవ్ చేసిన మార్గాలు లేవు',
    noSavedRoutesSub: 'ఇక్కడ సులభంగా ట్రాక్ చేయడానికి మీ మార్గాన్ని బుక్‌మార్క్ చేయండి',
    allClear: 'నెట్‌వర్క్ అంతటా అన్ని బస్సులు సాధారణంగా నడుస్తున్నాయి',
    availableSoon: 'త్వరలో అందుబాటులో ఉంటుంది',
    monthlyPass: 'అపరిమిత నెలవారీ పాస్',
    monthlyPassDesc: 'డిజిటల్ పాస్‌తో మీ రోజువారీ ప్రయాణంలో 40% వరకు ఆదా చేసుకోండి.',

    // Route Results & Cards
    eta: 'చేరే సమయం',
    crowd: 'రద్దీ',
    fare: 'ఛార్జీ',
    speed: 'వేగం',
    lowCrowd: 'తక్కువ రద్దీ',
    medCrowd: 'మధ్యస్థ రద్దీ',
    highCrowd: 'ఎక్కువ రద్దీ',
    returnDirection: 'తిరుగు ప్రయాణం',
    availableRoutes: 'అందుబాటులో ఉన్న మార్గాలు',
    noRoutesFound: 'మార్గాలు కనుగొనబడలేదు',
    planYourTrip: 'మీ ప్రయాణాన్ని ప్లాన్ చేయండి',
    popularDestinations: 'ప్రసిద్ధ గమ్యస్థానాలు',
    exploreMap: 'మొత్తం మ్యాప్‌ను చూడండి',

    // Map & Live Radar
    live: 'లైవ్',
    connecting: 'కనెక్ట్ అవుతోంది…',
    busesLive: 'బస్సులు లైవ్‌లో ఉన్నాయి',
    clearFilter: '✕ ఫిల్టర్ తీసివేయి',
    locate: 'నా స్థానం',
    nextStop: 'తదుపరి స్టాప్',
    passed: 'దాటింది',
    departed: 'బయలుదేరింది',

    // Safety & SOS
    sos: 'SOS',
    emergencyConfirmation: 'అత్యవసర నిర్ధారణ',
    emergencySubtitle: 'అత్యవసర సేవలు మరియు పరిచయాలకు తెలియజేయడానికి నిర్ధారించండి.',
    pressAndHold: 'నొక్కి పట్టుకోండి',
    alertSent: 'హెచ్చరిక పంపబడింది',
    sharingLiveLocation: 'లైవ్ లొకేషన్ పంచుకుంటున్నారు…',
    liveLocationShared: 'లైవ్ లొకేషన్ పంచుకోబడింది',
    notifyContacts: 'పరిచయాలకు తెలియజేయండి',
    edit: 'సవరించు',
    callEmergency: 'అత్యవసర సేవలకు కాల్ చేయండి (112)',
    cancelReturn: 'రద్దు చేసి వెనుకకు వెళ్ళండి',
    trustedContacts: 'అత్యవసర పరిచయాలు',
    addContact: 'పరిచయాన్ని జోడించండి',
    saveContact: 'సేవ్ చేయండి',

    // Alerts & Notifications
    pushNotifications: 'పుష్ నోటిఫికేషన్‌లు',
    manageTransitUpdates: 'మీ అన్ని నవీకరణలను నిర్వహించండి',
    activeSubscriptions: 'యాక్టివ్ మార్గ హెచ్చరికలు',
    recentUpdates: 'ఇటీవలి నవీకరణలు',
    noUpdates: 'ప్రస్తుతం సేవా అంతరాయాలు లేవు 🎉',
    pause: 'పాజ్ చేయి',
    resume: 'పునఃప్రారంభించు',
    delete: 'తొలగించు',
    setAlert: 'హెచ్చరికను సెట్ చేయండి',
    aiProactiveMode: 'AI-ప్రోయాక్టివ్ (సిఫార్సు చేయబడింది)',
    aiProactiveDesc: 'మీ స్థానం మరియు బస్సు రాక ఆధారంగా ఎప్పుడు బయలుదేరాలో తెలియజేస్తాము.',
    customAlarmMode: 'అనుకూల అలారం',
    customAlarmDesc: 'మీ స్టాప్‌కు బస్సు X నిమిషాల దూరంలో ఉన్నప్పుడు హెచ్చరిక పొందండి.',

    // Profile & Settings
    commuter: 'ప్రయాణీకుడు',
    trips: 'ప్రయాణాలు',
    timeSaved: 'ఆదా చేసిన సమయం',
    co2Saved: 'CO₂ ఆదా',
    settings: 'సెట్టింగ్‌లు',
    language: 'భాష',
    darkMode: 'డార్క్ మోడ్',
    logout: 'లాగ్ అవుట్',
    helpCenter: 'సహాయ కేంద్రం',
    safetySettings: 'భద్రత & SOS సెట్టింగ్‌లు',
    smartPickPreferences: 'స్మార్ట్ ఎంపిక ప్రాధాన్యతలు',
    weeklyReportCard: 'వారపు బస్సు రిపోర్ట్ కార్డు',

    // Report Card
    weeklyReport: 'వారపు నివేదిక కార్డు',
    onTimeRate: 'సమయపాలన రేటు',
    mostReliableRoute: 'అత్యంత నమ్మకమైన మార్గం',
    avgWaitTime: 'సగటు నిరీక్షణ సమయం',
    shareOnWhatsApp: 'WhatsApp లో భాగస్వామ్యం చేయండి',
  },

  kn: {
    // Top Bar & Branding
    appTitle: 'ನೆಕ್ಸ್ಟ್ ಬಸ್',
    appSubtitle: 'ಸುಲಭ ನಗರಾಂತರ ಪ್ರಯಾಣ',

    // Tabs
    home: 'ಮುಖಪುಟ',
    map: 'ನಕ್ಷೆ',
    search: 'ಹುಡುಕು',
    alerts: 'ಸೂಚನೆಗಳು',
    profile: 'ಪ್ರೊಫೈಲ್',

    // Home Dashboard
    whereToday: 'ಇಂದು ಎಲ್ಲಿಗೆ ಹೋಗಬೇಕು?',
    searchPlaceholder: 'ಗಮ್ಯಸ್ಥಾನಗಳು, ಮಾರ್ಗಗಳು ಅಥವಾ ನಿಲ್ದಾಣಗಳನ್ನು ಹುಡುಕಿ',
    findRoutes: 'ಮಾರ್ಗಗಳನ್ನು ಹುಡುಕಿ',
    from: 'ಇಂದ — ಹತ್ತುವ ನಿಲ್ದಾಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    to: 'ವರೆಗೆ — ಇಳಿಯುವ ನಿಲ್ದಾಣವನ್ನು ಆಯ್ಕೆಮಾಡಿ',
    smartPicks: 'ಸ್ಮಾರ್ಟ್ ಆಯ್ಕೆಗಳು',
    seeAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ',
    savedRoutes: 'ಉಳಿಸಿದ ಮಾರ್ಗಗಳು',
    manage: 'ನಿರ್ವಹಿಸಿ',
    transitUpdates: 'ಸಾರಿಗೆ ನವೀಕರಣಗಳು',
    activeBuses: 'ಸಕ್ರಿಯ ಬಸ್‌ಗಳು',
    network: 'ನೆಟ್‌ವರ್ಕ್',
    activeAlerts: 'ಸಕ್ರಿಯ ಸೂಚನೆಗಳು',
    noSavedRoutes: 'ಇನ್ನೂ ಯಾವುದೇ ಮಾರ್ಗಗಳನ್ನು ಉಳಿಸಿಲ್ಲ',
    noSavedRoutesSub: 'ತ್ವರಿತವಾಗಿ ಟ್ರ್ಯಾಕ್ ಮಾಡಲು ನಿಮ್ಮ ಮಾರ್ಗವನ್ನು ಉಳಿಸಿ',
    allClear: 'ಎಲ್ಲಾ ಬಸ್‌ಗಳು ನಿಗದಿತ ವೇಳೆಗೆ ಸರಿಯಾಗಿ ಚಲಿಸುತ್ತಿವೆ',
    availableSoon: 'ಶೀಘ್ರದಲ್ಲೇ ಲಭ್ಯವಿದೆ',
    monthlyPass: 'ಅನಿಯಮಿತ ಮಾಸಿಕ ಪಾಸ್',
    monthlyPassDesc: 'ಡಿಜಿಟಲ್ ಪಾಸ್‌ನೊಂದಿಗೆ ನಿಮ್ಮ ದೈನಂದಿನ ಪ್ರಯಾಣದಲ್ಲಿ 40% ವರೆಗೆ ಉಳಿಸಿ.',

    // Route Results & Cards
    eta: 'ಆಗಮನ ಸಮಯ',
    crowd: 'ಜನಸಂದಣಿ',
    fare: 'ದರ',
    speed: 'ವೇಗ',
    lowCrowd: 'ಕಡಿಮೆ ಜನಸಂದಣಿ',
    medCrowd: 'ಮಧ್ಯಮ ಜನಸಂದಣಿ',
    highCrowd: 'ಹೆಚ್ಚು ಜನಸಂದಣಿ',
    returnDirection: 'ಹಿಂತಿರುಗುವ ದಿಕ್ಕು',
    availableRoutes: 'ಲಭ್ಯವಿರುವ ಮಾರ್ಗಗಳು',
    noRoutesFound: 'ಯಾವುದೇ ಮಾರ್ಗಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
    planYourTrip: 'ನಿಮ್ಮ ಪ್ರಯಾಣವನ್ನು ಯೋಜಿಸಿ',
    popularDestinations: 'ಜನಪ್ರಿಯ ತಾಣಗಳು',
    exploreMap: 'ಸಂಪೂರ್ಣ ನಕ್ಷೆಯನ್ನು ಅನ್ವೇಷಿಸಿ',

    // Map & Live Radar
    live: 'ಲೈವ್',
    connecting: 'ಸಂಪರ್ಕಿಸಲಾಗುತ್ತಿದೆ…',
    busesLive: 'ಬಸ್‌ಗಳು ಲೈವ್ ಆಗಿವೆ',
    clearFilter: '✕ ಫಿಲ್ಟರ್ ತೆಗೆದುಹಾಕಿ',
    locate: 'ನನ್ನ ಸ್ಥಳ',
    nextStop: 'ಮುಂದಿನ ನಿಲ್ದಾಣ',
    passed: 'ದಾಟಿದೆ',
    departed: 'ಹೊರಟಿದೆ',

    // Safety & SOS
    sos: 'SOS',
    emergencyConfirmation: 'ತುರ್ತು ದೃಢೀಕರಣ',
    emergencySubtitle: 'ತುರ್ತು ಸೇವೆಗಳು ಮತ್ತು ವಿಶ್ವಾಸಾರ್ಹ ಸಂಪರ್ಕಗಳಿಗೆ ತಿಳಿಸಲು ದೃಢೀಕರಿಸಿ.',
    pressAndHold: 'ಒತ್ತಿ ಹಿಡಿದುಕೊಳ್ಳಿ',
    alertSent: 'ಸೂಚನೆ ಕಳುಹಿಸಲಾಗಿದೆ',
    sharingLiveLocation: 'ಲೈವ್ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳಲಾಗುತ್ತಿದೆ…',
    liveLocationShared: 'ಲೈವ್ ಸ್ಥಳವನ್ನು ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ',
    notifyContacts: 'ಸಂಪರ್ಕಗಳಿಗೆ ತಿಳಿಸಿ',
    edit: 'ತಿದ್ದು',
    callEmergency: 'ತುರ್ತು ಸೇವೆಗಳಿಗೆ ಕರೆ ಮಾಡಿ (112)',
    cancelReturn: 'ರದ್ದುಗೊಳಿಸಿ ಹಿಂತಿರುಗಿ',
    trustedContacts: 'ತುರ್ತು ಸಂಪರ್ಕಗಳು',
    addContact: 'ಸಂಪರ್ಕ ಸೇರಿಸಿ',
    saveContact: 'ಉಳಿಸಿ',

    // Alerts & Notifications
    pushNotifications: 'ಪುಶ್ ಅಧಿಸೂಚನೆಗಳು',
    manageTransitUpdates: 'ನಿಮ್ಮ ಎಲ್ಲಾ ಸಾರಿಗೆ ನವೀಕರಣಗಳನ್ನು ನಿರ್ವಹಿಸಿ',
    activeSubscriptions: 'ಸಕ್ರಿಯ ಮಾರ್ಗ ಚಂದಾದಾರಿಕೆಗಳು',
    recentUpdates: 'ಇತ್ತೀಚಿನ ನವೀಕರಣಗಳು',
    noUpdates: 'ಸದ್ಯ ಯಾವುದೇ ಸೇವಾ ಅಡೆತಡೆಗಳಿಲ್ಲ 🎉',
    pause: 'ವಿರಾಮಗೊಳಿಸಿ',
    resume: 'ಮುಂದುವರಿಸಿ',
    delete: 'ಅಳಿಸಿ',
    setAlert: 'ಸೂಚನೆ ಹೊಂದಿಸಿ',
    aiProactiveMode: 'AI-ಪ್ರೊಆಕ್ಟಿವ್ (ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ)',
    aiProactiveDesc: 'ನಿಮ್ಮ ಸ್ಥಳ ಮತ್ತು ಬಸ್ ಆಗಮನದ ಆಧಾರದ ಮೇಲೆ ಯಾವಾಗ ಹೊರಡಬೇಕೆಂದು ನಾವು ತಿಳಿಸುತ್ತೇವೆ.',
    customAlarmMode: 'ಕಸ್ಟಮ್ ಅಲಾರಾಂ',
    customAlarmDesc: 'ಬಸ್ ನಿಮ್ಮ ನಿಲ್ದಾಣದಿಂದ X ನಿಮಿಷಗಳ ದೂರದಲ್ಲಿದ್ದಾಗ ಸೂಚನೆ ಪಡೆಯಿರಿ.',

    // Profile & Settings
    commuter: 'ಪ್ರಯಾಣಿಕ',
    trips: 'ಪ್ರಯಾಣಗಳು',
    timeSaved: 'ಉಳಿಸಿದ ಸಮಯ',
    co2Saved: 'CO₂ ಉಳಿತಾಯ',
    settings: 'ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    language: 'ಭಾಷೆ',
    darkMode: 'ಡಾರ್ಕ್ ಮೋಡ್',
    logout: 'ಲಾಗ್ ಔಟ್',
    helpCenter: 'ಸಹಾಯ ಕೇಂದ್ರ',
    safetySettings: 'ಸುರಕ್ಷತೆ & SOS ಸೆಟ್ಟಿಂಗ್‌ಗಳು',
    smartPickPreferences: 'ಸ್ಮಾರ್ಟ್ ಆಯ್ಕೆ ಆದ್ಯತೆಗಳು',
    weeklyReportCard: 'ಸಾಪ್ತಾಹಿಕ ಬಸ್ ವರದಿ ಕಾರ್ಡ್',

    // Report Card
    weeklyReport: 'ಸಾಪ್ತಾಹಿಕ ವರದಿ ಕಾರ್ಡ್',
    onTimeRate: 'ಸಮಯಪಾಲನೆ ದರ',
    mostReliableRoute: 'ಅತ್ಯಂತ ವಿಶ್ವಾಸಾರ್ಹ ಮಾರ್ಗ',
    avgWaitTime: 'ಸರಾಸರಿ ಕಾಯುವ ಸಮಯ',
    shareOnWhatsApp: 'WhatsApp ನಲ್ಲಿ ಹಂಚಿಕೊಳ್ಳಿ',
  },
};

export const getTranslation = (key: string, language: Language = 'en'): string => {
  return translations[language]?.[key] || translations['en']?.[key] || key;
};
